SRC		=	main.cpp Bureaucrat.cpp
HDRS	=	Bureaucrat.hpp
NAME	=	bureaucrat

.PHONY	:	all fclean

all		:	$(NAME)

$(NAME)	:	$(SRC) $(HDRS)
			c++ -Wall -Wextra -Werror -std=c++98 $(SRC) -o $(NAME)

fclean	:	
			rm -f $(NAME)